### ISSUE TITLE
Consider client app framework to build for all platforms from one code

### ISSUE THREAD

**Issue by evemorgen** [thomann/plotAR#1]
Hi,
I've poked around for a bit and found out that there are two different (out of sync feature-wise) implementations for main mobile platforms ([IOS](https://github.com/thomann/PlotAR-ios), [Android](https://github.com/thomann/plotVR-android)). Maintaining, keeping and deploying two different builds seems like a hard job. Wouldn't it be nice to run application code once and run it on both platforms? 

There exists a couple of such solutions like [ReactNative](https://facebook.github.io/react-native/) or [Cordova](https://cordova.apache.org/) (and probably many others) that make it possible. I've researched for a bit and it seems that both of them support AR + VR ([ReactNative](https://github.com/viromedia/viro), [Cordova](http://docs.phonegap.com/tutorials/develop/wikitude/))

**Comment by thomann** [comment]
Hey @evemorgen,

It has been a long time - sorry for not answering sooner.

Using these Frameworks is certainly worth taking into consideration. However in the meantime, AR-FileFormats started becoming really usable out-of-the-box, so PlotAR now is targetting those.
